import { slugify } from '@/common/utils';
import { Partner } from "@/common/interfaces";
import { FEATURED_AREAS } from '@/common/constants';
import { PARTNER_CATEGORIES } from './partnerCategories';

export const PARTNERS: Partner[] = [
  {
    name: 'Friedrich Ebert Stiftung',
    alias: 'FES',
    image: '/images/home/partners/FES.png',
    cardImage: '/images/partners/card-logos/FES.jpg',
    detailImage: '/images/partners/card-logos/FES.jpg',
    category: PARTNER_CATEGORIES[2],
    isLarge: false,
    email: 'prensamisiononu@un.org',
    phone: '+57 (1) 347 3077 / - 3092',
    webSrc: '#',
    youtubeSrc: '#',
    description: `La Friedrich-Ebert-Stiftung (FES), fundada en 1925, es la fundación política más antigua de Alemania. Esta institución se fundó como legado político del primer presidente alemán elegido democráticamente, Friedrich Ebert, a quien debe su nombre así como los principios que la rigen. En calidad de fundación política cercana a un partido, nuestro trabajo se rige por los valores fundamentales de la democracia social: libertad, justicia y solidaridad. Estos valores nos vinculan de una forma ideal a la socialde- mocracia y a los sindicatos libres. Siendo una institución sin ánimo de lucro, diseñamos nuestras actividades de un modo independiente y autosuficiente.`,
    results: [
      {
        category: 'Nuestros Aliados',
        image: '/images/experiences/thematic-areas/science/no-image.jpg',
        title: 'Curso de formación A',
        date: '16 de septiembre de 2022',
        url: '#',
        area: { ...FEATURED_AREAS.training }
      },
      {
        category: 'Nuestros Aliados',
        image: '/images/experiences/thematic-areas/science/no-image.jpg',
        title: 'Curso de formación B',
        date: '16 de septiembre de 2022',
        url: '#',
        area: { ...FEATURED_AREAS.training }
      },
      {
        category: 'Nuestros Aliados',
        image: '/images/experiences/thematic-areas/science/no-image.jpg',
        title: 'Curso de formación C',
        date: '16 de septiembre de 2022',
        url: '#',
        area: { ...FEATURED_AREAS.training }
      },
    ],
  },
  {
    name: 'Jurisdicción Especial para la Paz',
    alias: 'JEP',
    image: '/images/home/partners/JEP.png',
    cardImage: '/images/partners/card-logos/JEP.jpg',
    detailImage: '/images/partners/card-logos/JEP.jpg',
    category: PARTNER_CATEGORIES[0],
    isLarge: false,
    email: 'info@jep.gov.co',
    phone: '(+57) (1) 7440041',
    webSrc: '#',
    youtubeSrc: '#',
    description: 'La Jurisdicción Especial para la Paz (JEP) es el componente de justicia del Sistema Integral de Verdad, Justicia, Reparación y no Repetición, creado por el Acuerdo de Paz entre el Gobierno Nacional y las Farc-EP. La JEP tiene la función de administrar justicia transicional y conocer de los delitos cometidos en el marco del conflicto armado que se hubieran cometido antes del 1 de diciembre de 2016. La existencia de la JEP no podrá ser superior a 20 años.',
    results: [
      {
        category: 'Nuestros Aliados',
        image: '/images/experiences/thematic-areas/science/no-image.jpg',
        title: 'Curso de formación A',
        date: '16 de septiembre de 2022',
        url: '#',
        area: { ...FEATURED_AREAS.training }
      },
      {
        category: 'Nuestros Aliados',
        image: '/images/experiences/thematic-areas/science/no-image.jpg',
        title: 'Curso de formación B',
        date: '16 de septiembre de 2022',
        url: '#',
        area: { ...FEATURED_AREAS.training }
      },
      {
        category: 'Nuestros Aliados',
        image: '/images/experiences/thematic-areas/science/no-image.jpg',
        title: 'Curso de formación C',
        date: '16 de septiembre de 2022',
        url: '#',
        area: { ...FEATURED_AREAS.training }
      },
    ],
  },
  {
    name: 'Unidad de Búsqueda de Personas dadas por Desaparecidas',
    alias: 'UBPD',
    image: '/images/home/partners/UBPD.png',
    cardImage: '/images/partners/card-logos/UBPD.jpg',
    detailImage: '/images/partners/card-logos/UBPD.jpg',
    category: PARTNER_CATEGORIES[0],
    isLarge: true,
    email: 'servicioalciudadano@ubpdbusquedadesaparecidos.co',
    phone: '018000-117175',
    webSrc: '#',
    youtubeSrc: '#',
    description: `La Unidad de Búsqueda de Personas dadas por Desaparecidas en el contexto y en razón del conflicto armado (UBPD) es una entidad del Estado de carácter humanitario y extrajudicial, autónomo e independiente dentro del Sistema Integral de Verdad, Justicia, Reparación y No Repetición (SIVJRNR), que dirige, coordina y contribuye a la búsqueda de personas dadas por desaparecidas en el marco del conflicto armado, que se encuentren con vida y, en los casos de fallecimiento, cuando sea posible, la recuperación, identificación y entrega digna de cuerpos. Son competencia de la UBPD las desapariciones ocurridas antes del 1ro de diciembre de 2016 (fecha de entrada en vigencia de los Acuerdos), sucedidas en el contexto y en razón del conflicto armado, correspondientes a desaparición forzada, secuestro, reclutamiento ilícito, durante las hostilidades.`,
    results: [
      {
        category: 'Nuestros Aliados',
        image: '/images/experiences/thematic-areas/science/no-image.jpg',
        title: 'Curso de formación A',
        date: '16 de septiembre de 2022',
        url: '#',
        area: { ...FEATURED_AREAS.training }
      },
      {
        category: 'Nuestros Aliados',
        image: '/images/experiences/thematic-areas/science/no-image.jpg',
        title: 'Curso de formación B',
        date: '16 de septiembre de 2022',
        url: '#',
        area: { ...FEATURED_AREAS.training }
      },
      {
        category: 'Nuestros Aliados',
        image: '/images/experiences/thematic-areas/science/no-image.jpg',
        title: 'Curso de formación C',
        date: '16 de septiembre de 2022',
        url: '#',
        area: { ...FEATURED_AREAS.training }
      },
    ],
  },
  {
    name: 'Comisión de la Verdad',
    alias: 'Comisión de la Verdad',
    image: '/images/home/partners/CV.png',
    cardImage: '/images/partners/card-logos/CV.jpg',
    detailImage: '/images/partners/card-logos/CV.jpg',
    category: PARTNER_CATEGORIES[0],
    isLarge: false,
    email: 'info@comisiondelaverdad.co',
    phone: '(+57) (1) 7444344',
    webSrc: '#',
    youtubeSrc: '#',
    description: `En el marco del Acuerdo Final para la terminación del conflicto y la construcción de una paz estable y duradera, mediante el Acto Legislativo 01 de 2017 y el Decreto 588 de 2017, se creó la Comisión para el Esclarecimiento de la Verdad, la Convivencia y la No Repetición, como un mecanismo de carácter temporal y extrajudicial del Sistema Integral de Verdad, Justicia, Reparación y No Repetición - SIVJRNR, para conocer la verdad de lo ocurrido en el marco del conflicto armado y contribuir al esclarecimiento de las violaciones e infracciones cometidas durante el mismo y ofrecer una explicación amplia de su complejidad a toda la sociedad. Busca satisfacer el derecho de las víctimas y de la sociedad a la verdad, promover el reconocimiento de lo sucedido, la convivencia en los territorios y contribuir a sentar las bases para la no repetición, mediante un proceso de participación amplio y plural para la construcción de paz.`,
    results: [
      {
        category: 'Nuestros Aliados',
        image: '/images/experiences/thematic-areas/science/no-image.jpg',
        title: 'Informe final, Comisión de la verdad',
        date: '2022',
        url: '#',
        area: { ...FEATURED_AREAS.articles }
      },
    ],
  },
  {
    name: 'Instituto Colombo-Alemán para la Paz',
    alias: 'ICAP',
    image: '/images/home/partners/CAPAZ.png',
    cardImage: '/images/partners/card-logos/CAPAZ.jpg',
    detailImage: '/images/partners/card-logos/CAPAZ.jpg',
    category: PARTNER_CATEGORIES[2],
    isLarge: false,
    email: 'info@www.instituto-capaz.org',
    phone: '+57 (1)3422340 Ext. 29981',
    webSrc: '#',
    youtubeSrc: '#',
    description: `El Instituto CAPAZ es una plataforma de cooperación entre Colombia y Alemania que promueve el intercambio de conocimientos y experiencias en temas de construcción de paz, mediante la conformación de redes entre universidades, centros de investigación, organizaciones de la sociedad civil y entidades gubernamentales, que actúan en el ámbito territorial. CAPAZ promueve actividades de investigación, enseñanza y asesoría, que permiten nuevas aproximaciones al entendimiento de la paz y el conflicto, transmiten conocimiento a la sociedad y plantean respuestas a los múltiples desafíos de una sociedad en transición. El Instituto CAPAZ es un Centro de Excelencia en Investigación y Docencia financiado por el Servicio Alemán de Intercambio Académico (DAAD), con recursos del Ministerio Federal de Asuntos Exteriores de Alemania.`,
    results: [
      {
        category: 'Nuestros Aliados',
        image: '/images/experiences/thematic-areas/science/no-image.jpg',
        title: 'Curso de formación A',
        date: '16 de septiembre de 2022',
        url: '#',
        area: { ...FEATURED_AREAS.training }
      },
      {
        category: 'Nuestros Aliados',
        image: '/images/experiences/thematic-areas/science/no-image.jpg',
        title: 'Curso de formación B',
        date: '16 de septiembre de 2022',
        url: '#',
        area: { ...FEATURED_AREAS.training }
      },
      {
        category: 'Nuestros Aliados',
        image: '/images/experiences/thematic-areas/science/no-image.jpg',
        title: 'Curso de formación C',
        date: '16 de septiembre de 2022',
        url: '#',
        area: { ...FEATURED_AREAS.training }
      },
    ],
  },
  {
    name: 'Agencia para la Reincorporación y la Normalización',
    alias: 'ARN',
    image: '/images/home/partners/ARN.png',
    cardImage: '/images/partners/card-logos/ARN.jpg',
    detailImage: '/images/partners/card-logos/ARN.jpg',
    category: PARTNER_CATEGORIES[1],
    isLarge: true,
    email: 'atencion@reincorporacion.gov.co',
    phone: '+57 601 4430020.',
    webSrc: '#',
    youtubeSrc: '#',
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

    Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?`,
    results: [
      {
        category: 'Nuestros Aliados',
        image: '/images/experiences/thematic-areas/science/no-image.jpg',
        title: 'Curso de formación A',
        date: '16 de septiembre de 2022',
        url: '#',
        area: { ...FEATURED_AREAS.training }
      },
      {
        category: 'Nuestros Aliados',
        image: '/images/experiences/thematic-areas/science/no-image.jpg',
        title: 'Curso de formación B',
        date: '16 de septiembre de 2022',
        url: '#',
        area: { ...FEATURED_AREAS.training }
      },
      {
        category: 'Nuestros Aliados',
        image: '/images/experiences/thematic-areas/science/no-image.jpg',
        title: 'Curso de formación C',
        date: '16 de septiembre de 2022',
        url: '#',
        area: { ...FEATURED_AREAS.training }
      },
    ],
  },
  {
    name: 'Sistema Universitario Estatal - Mesa de Gobernabilidad y Paz',
    alias: 'SUE',
    image: '/images/home/partners/SUE.png',
    cardImage: '/images/partners/card-logos/SUE.jpg',
    detailImage: '/images/partners/card-logos/SUE.jpg',
    category: PARTNER_CATEGORIES[1],
    isLarge: true,
    email: '',
    phone: '',
    webSrc: '',
    youtubeSrc: '',
    description: '',
    results: [],
  },
  // {
  //   name: 'Agencia de la Renovación del Territorio',
  //   image: '/images/home/partners/ART.png',
  //   cardImage: '/images/partners/card-logos/ART.jpg',
  //   detailImage: '/images/partners/card-logos/ART.jpg',
  //   category: PARTNER_CATEGORIES[1],
  //   isLarge: true,
  //   email: '',
  //   phone: '',
  //   webSrc: '',
  //   youtubeSrc: '',
  // },
  // {
  //   name: 'Dirección de Sustitución de Cultivos de Uso Ilícito',
  //   image: '/images/home/partners/DSCUI.png',
  //   cardImage: '/images/partners/card-logos/DSCUI.jpg',
  //   detailImage: '/images/partners/card-logos/DSCUI.jpg',
  //   category: PARTNER_CATEGORIES[1],
  //   isLarge: true,
  //   email: '',
  //   phone: '',
  //   webSrc: '',
  //   youtubeSrc: '',
  // },
  // {
  //   name: 'Unidad Policial para la Edificación de la Paz',
  //   image: '',
  //   cardImage: '/images/partners/card-logos/UNIPEP.jpg',
  //   detailImage: '/images/partners/card-logos/UNIPEP.jpg',
  //   category: PARTNER_CATEGORIES[1],
  //   isLarge: true,
  //   email: '',
  //   phone: '',
  //   webSrc: '',
  //   youtubeSrc: '',
  // },
  // {
  //   name: 'Instituto Geográfico Agustín Codazzi',
  //   image: '',
  //   cardImage: '/images/partners/card-logos/IGAC.jpg',
  //   detailImage: '/images/partners/card-logos/IGAC.jpg',
  //   category: PARTNER_CATEGORIES[1],
  //   isLarge: true,
  //   email: '',
  //   phone: '',
  //   webSrc: '',
  //   youtubeSrc: '',
  // },
  // {
  //   name: 'Red SaludPaz',
  //   image: '',
  //   cardImage: '/images/partners/card-logos/RSP.jpg',
  //   detailImage: '/images/partners/card-logos/RSP.jpg',
  //   category: PARTNER_CATEGORIES[1],
  //   isLarge: true,
  //   email: '',
  //   phone: '',
  //   webSrc: '',
  //   youtubeSrc: '',
  // },
  // Internacionales
  {
    name: 'Misión de Verificación de la ONU en Colombia',
    alias: 'MVOC',
    image: '/images/home/partners/MVOC.png',
    cardImage: '/images/partners/card-logos/MVOC.jpg',
    detailImage: '/images/partners/card-logos/MVOC.jpg',
    category: PARTNER_CATEGORIES[2],
    isLarge: true,
    email: 'prensamisiononu@un.org',
    phone: '(1) 7455977',
    webSrc: '#',
    youtubeSrc: '#',
    description: `La Misión de Verificación de las Naciones Unidas verificará la reincorporación política, económica y social; y las garantías de seguridad para los integrantes de la FARC, sus familias y para las comunidades.`,
    results: [
      {
        category: 'Nuestros Aliados',
        image: '/images/experiences/thematic-areas/science/no-image.jpg',
        title: 'Curso de formación A',
        date: '16 de septiembre de 2022',
        url: '#',
        area: { ...FEATURED_AREAS.training }
      },
      {
        category: 'Nuestros Aliados',
        image: '/images/experiences/thematic-areas/science/no-image.jpg',
        title: 'Curso de formación B',
        date: '16 de septiembre de 2022',
        url: '#',
        area: { ...FEATURED_AREAS.training }
      },
      {
        category: 'Nuestros Aliados',
        image: '/images/experiences/thematic-areas/science/no-image.jpg',
        title: 'Curso de formación C',
        date: '16 de septiembre de 2022',
        url: '#',
        area: { ...FEATURED_AREAS.training }
      },
    ],
  },

  // {
  //   name: 'Oficina de DDHH de la ONU',
  //   alias: 'ODHO',
  //   image: '/images/home/partners/ODHONU.png',
  //   cardImage: '/images/partners/card-logos/ODHONU.jpg',
  //   detailImage: '/images/partners/card-logos/ODHONU.jpg',
  //   category: PARTNER_CATEGORIES[2],
  //   isLarge: false,
  //   email: '',
  //   phone: '',
  //   webSrc: '',
  //   youtubeSrc: '',
  // },
  // {
  //   name: 'Oficina de Drogas y Crimen de la ONU',
  //   alias: 'IDCO',
  //   image: '/images/home/partners/UNODC.png',
  //   cardImage: '/images/partners/card-logos/UNODC.jpg',
  //   detailImage: '/images/partners/card-logos/UNODC.jpg',
  //   category: PARTNER_CATEGORIES[2],
  //   isLarge: false,
  //   email: '',
  //   phone: '',
  //   webSrc: '',
  //   youtubeSrc: '',
  // },
].map((partner) => ({
  ...partner,
  src: `/nuestros-aliados/${partner.category.slug}/${slugify(partner.name)}`,
}));
