import { Partner } from "@/common/interfaces";
import { PARTNER_CATEGORIES } from './partnerCategories';

export const PARTNERS: Partner[] = [
  // SIP
  {
    name: 'Comisión de la Verdad',
    image: '/images/home/partners/CV.png',
    cardImage: '/images/partners/card-logos/CV.jpg',
    category: PARTNER_CATEGORIES[0],
    src: '',
    isLarge: false,
  },
  {
    name: 'Jurisdicción Especial para la Paz',
    image: '/images/home/partners/JEP.png',
    cardImage: '/images/partners/card-logos/JEP.jpg',
    category: PARTNER_CATEGORIES[0],
    src: '',
    isLarge: false,
  },
  {
    name: 'Unidad de Búsqueda de Personas dadas por Desaparecidas',
    image: '/images/home/partners/UBPD.png',
    cardImage: '/images/partners/card-logos/UBPD.jpg',
    category: PARTNER_CATEGORIES[0],
    src: '',
    isLarge: true,
  },
  // Gubernamental
  {
    name: 'Agencia para la Reincorporación y la Normalización',
    image: '/images/home/partners/ARN.png',
    cardImage: '/images/partners/card-logos/ARN.jpg',
    category: PARTNER_CATEGORIES[1],
    src: '',
    isLarge: true,
  },
  {
    name: 'Agencia de la Renovación del Territorio',
    image: '/images/home/partners/ART.png',
    cardImage: '/images/partners/card-logos/ART.jpg',
    category: PARTNER_CATEGORIES[1],
    src: '',
    isLarge: true,
  },
  {
    name: 'Dirección de Sustitución de Cultivos de Uso Ilícito',
    image: '/images/home/partners/DSCUI.png',
    cardImage: '/images/partners/card-logos/DSCUI.jpg',
    category: PARTNER_CATEGORIES[1],
    src: '',
    isLarge: true,
  },
  {
    name: 'Sistema Universitario Estatal - Mesa de Gobernabilidad y Paz',
    image: '',
    cardImage: '/images/partners/card-logos/SUE.jpg',
    category: PARTNER_CATEGORIES[1],
    src: '',
    isLarge: true,
  },
  {
    name: 'Unidad Policial para la Edificación de la Paz',
    image: '',
    cardImage: '/images/partners/card-logos/UNIPEP.jpg',
    category: PARTNER_CATEGORIES[1],
    src: '',
    isLarge: true,
  },
  {
    name: 'Instituto Geográfico Agustín Codazzi',
    image: '',
    cardImage: '/images/partners/card-logos/IGAC.jpg',
    category: PARTNER_CATEGORIES[1],
    src: '',
    isLarge: true,
  },
  {
    name: 'Red SaludPaz',
    image: '',
    cardImage: '/images/partners/card-logos/RSP.jpg',
    category: PARTNER_CATEGORIES[1],
    src: '',
    isLarge: true,
  },
  // Internacionales
  {
    name: 'Misión de Verificación de la ONU en Colombia',
    image: '/images/home/partners/MVOC.png',
    cardImage: '/images/partners/card-logos/MVOC.jpg',
    category: PARTNER_CATEGORIES[2],
    src: '',
    isLarge: true,
  },
  {
    name: 'Instituto Colombo-Alemán para la Paz',
    image: '/images/home/partners/CAPAZ.png',
    cardImage: '/images/partners/card-logos/CAPAZ.jpg',
    category: PARTNER_CATEGORIES[2],
    src: '',
    isLarge: false,
  },
  {
    name: 'Friedrich Ebert Stiftung',
    image: '/images/home/partners/FES.png',
    cardImage: '/images/partners/card-logos/FES.jpg',
    category: PARTNER_CATEGORIES[2],
    src: '',
    isLarge: false,
  },
  {
    name: 'Oficina de DDHH de la ONU',
    image: '/images/home/partners/ODHONU.png',
    cardImage: '/images/partners/card-logos/ODHONU.jpg',
    category: PARTNER_CATEGORIES[2],
    src: '',
    isLarge: false,
  },
  {
    name: 'Oficina de Drogas y Crimen de la ONU',
    image: '/images/home/partners/UNODC.png',
    cardImage: '/images/partners/card-logos/UNODC.jpg',
    category: PARTNER_CATEGORIES[2],
    src: '',
    isLarge: false,
  },
];
