import { Person } from '@/common/interfaces';

export const TEAM_MEMBERS: Person[] = [
  {
    name: 'Doris Adriana Santos Caicedo',
    image: '/src/assets/images/about-us/team/doris-santos.jpeg',
    position: 'Coordinadora Red Paz Unal',
    email: 'correounal@unal.edu.co',
    phone: '3165000 Ext. 00000',
    link: { label: 'Ver perfil', src: '#' },
    highLight: true,
  },
  {
    name: 'Juan Alfonso de la Rosa Munar',
    image: '/src/assets/images/about-us/team/doris-santos.jpeg',
    position: 'Miembro actual Red Paz Unal',
    email: 'correounal@unal.edu.co',
    phone: '3165000 Ext. 00000',
    link: { label: 'Ver perfil', src: '#' },
    highLight: false,
  },
  {
    name: 'Ana Patricia Noguera de E.',
    image: '/src/assets/images/about-us/team/doris-santos.jpeg',
    position: 'Miembro actual Red Paz Unal',
    email: 'correounal@unal.edu.co',
    phone: '3165000 Ext. 00000',
    link: { label: 'Ver perfil', src: '#' },
    highLight: false,
  },
  {
    name: 'Adriana Patricia Muñoz Ramírez',
    image: '/src/assets/images/about-us/team/doris-santos.jpeg',
    position: 'Miembro actual Red Paz Unal',
    email: 'correounal@unal.edu.co',
    phone: '3165000 Ext. 00000',
    link: { label: 'Ver perfil', src: '#' },
    highLight: false,
  },
  {
    name: 'Adriana Villota',
    image: '/src/assets/images/about-us/team/doris-santos.jpeg',
    position: 'Miembro actual Red Paz Unal',
    email: 'correounal@unal.edu.co',
    phone: '3165000 Ext. 00000',
    link: { label: 'Ver perfil', src: '#' },
    highLight: false,
  },
  {
    name: 'Bois Duarte Caviedes',
    image: '/src/assets/images/about-us/team/doris-santos.jpeg',
    position: 'Miembro actual Red Paz Unal',
    email: 'correounal@unal.edu.co',
    phone: '3165000 Ext. 00000',
    link: { label: 'Ver perfil', src: '#' },
    highLight: false,
  },
  {
    name: 'Carlos Eduardo Satizábal A.',
    image: '/src/assets/images/about-us/team/doris-santos.jpeg',
    position: 'Miembro actual Red Paz Unal',
    email: 'correounal@unal.edu.co',
    phone: '3165000 Ext. 00000',
    link: { label: 'Ver perfil', src: '#' },
    highLight: false,
  },
  {
    name: 'Carlos Eduardo Barriga Acevedo',
    image: '/src/assets/images/about-us/team/doris-santos.jpeg',
    position: 'Miembro actual Red Paz Unal',
    email: 'correounal@unal.edu.co',
    phone: '3165000 Ext. 00000',
    link: { label: 'Ver perfil', src: '#' },
    highLight: false,
  },
  {
    name: 'Claudia Patricia Sierra Pardo',
    image: '/src/assets/images/about-us/team/doris-santos.jpeg',
    position: 'Miembro actual Red Paz Unal',
    email: 'correounal@unal.edu.co',
    phone: '3165000 Ext. 00000',
    link: { label: 'Ver perfil', src: '#' },
    highLight: false,
  },
  {
    name: 'Fabio Rodrigo Leiva Barón',
    image: '/src/assets/images/about-us/team/doris-santos.jpeg',
    position: 'Miembro actual Red Paz Unal',
    email: 'correounal@unal.edu.co',
    phone: '3165000 Ext. 00000',
    link: { label: 'Ver perfil', src: '#' },
    highLight: false,
  },
  {
    name: 'James León Parra-Monsalve',
    image: '/src/assets/images/about-us/team/doris-santos.jpeg',
    position: 'Miembro actual Red Paz Unal',
    email: 'correounal@unal.edu.co',
    phone: '3165000 Ext. 00000',
    link: { label: 'Ver perfil', src: '#' },
    highLight: false,
  },
  {
    name: 'JJovani Alberto Jiménez Builes',
    image: '/src/assets/images/about-us/team/doris-santos.jpeg',
    position: 'Miembro actual Red Paz Unal',
    email: 'correounal@unal.edu.co',
    phone: '3165000 Ext. 00000',
    link: { label: 'Ver perfil', src: '#' },
    highLight: false,
  },
  {
    name: 'Karol Bibiana Barragán Fonseca',
    image: '/src/assets/images/about-us/team/doris-santos.jpeg',
    position: 'Miembro actual Red Paz Unal',
    email: 'correounal@unal.edu.co',
    phone: '3165000 Ext. 00000',
    link: { label: 'Ver perfil', src: '#' },
    highLight: false,
  },
  {
    name: 'Maria Clemencia Castro Vergara',
    image: '/src/assets/images/about-us/team/doris-santos.jpeg',
    position: 'Miembro actual Red Paz Unal',
    email: 'correounal@unal.edu.co',
    phone: '3165000 Ext. 00000',
    link: { label: 'Ver perfil', src: '#' },
    highLight: false,
  },
  {
    name: 'Marina Sánchez de Praguer',
    image: '/src/assets/images/about-us/team/doris-santos.jpeg',
    position: 'Miembro actual Red Paz Unal',
    email: 'correounal@unal.edu.co',
    phone: '3165000 Ext. 00000',
    link: { label: 'Ver perfil', src: '#' },
    highLight: false,
  },
  {
    name: 'Mario Esteban Hernández Álvarez',
    image: '/src/assets/images/about-us/team/doris-santos.jpeg',
    position: 'Miembro actual Red Paz Unal',
    email: 'correounal@unal.edu.co',
    phone: '3165000 Ext. 00000',
    link: { label: 'Ver perfil', src: '#' },
    highLight: false,
  },
  {
    name: 'Rafael Antonio Malagón Oviedo',
    image: '/src/assets/images/about-us/team/doris-santos.jpeg',
    position: 'Miembro actual Red Paz Unal',
    email: 'correounal@unal.edu.co',
    phone: '3165000 Ext. 00000',
    link: { label: 'Ver perfil', src: '#' },
    highLight: false,
  },
];

export default TEAM_MEMBERS;
