import { Person } from '@/common/interfaces';

export const TEAM_MEMBERS: Person[] = [
  {
    name: 'Doris Adriana Santos Caicedo',
    image: '/images/about-us/team/doris-santos.png',
    faculty: 'Facultad de Ciencias Humanas',
    location: 'Sede Bogotá',
    email: 'correounal@unal.edu.co',
  },
  {
    name: 'Diana Hincapié',
    image: '/images/about-us/team/diana-hincapie.png',
    faculty: 'Facultad de Ciencias Políticas',
    location: 'Sede Bogotá',
    email: 'correounal@unal.edu.co',
  },
  // {
  //   name: 'Juan Alfonso de la Rosa Munar',
  //   image: '/images/about-us/team/doris-santos.jpeg',
  //   faculty: 'Facultad de Artes',
  //   location: 'Sede Bogotá',
  //   email: 'correounal@unal.edu.co',
  // },
  {
    name: 'Adriana Patricia Muñoz Ramírez',
    image: '/images/about-us/team/adriana-munoz.png',
    faculty: 'Fac. de Medicina Veterinaria y Zootecnia',
    location: 'Sede Bogotá',
    email: 'apmunozr@unal.edu.co',
  },
  // {
  //   name: 'Ana Patricia Noguera de E.',
  //   image: '/images/about-us/team/doris-santos.jpeg',
  //   faculty: 'Facultad de Adminiztración',
  //   location: 'Sede Manizales',
  //   email: 'apnoguerad@unal.edu.co',
  // },
  {
    name: 'Adriana Villota',
    image: '/images/about-us/team/woman-default.jpg',
    faculty: 'Facultad de Administración',
    location: 'Sede Manizales',
    email: 'adrianavimar@unal.edu.co',
  },
  {
    name: 'Jairo Alexis Rodríguez López',
    image: '/images/about-us/team/jairo-rodriguez.jpg',
    faculty: 'Facultad de Ciencias',
    location: 'Sede Bogotá',
    email: 'correounal@unal.edu.co',
  },
  // {
  //   name: 'Bois Duarte Caviedes',
  //   image: '/images/about-us/team/doris-santos.jpeg',
  //   faculty: 'Centro de pensamiento y seguimiento',
  //   location: '--',
  //   email: 'bduartec@unal.edu.co',
  // },
  {
    name: 'Carlos Eduardo Satizábal A.',
    image: '/images/about-us/team/carlos-satizabal.png',
    faculty: 'Facultad de Artes',
    location: 'Sede Bogotá',
    email: 'cesatizabala@unal.edu.co',
  },
  {
    name: 'Carlos Eduardo Barriga Acevedo',
    image: '/images/about-us/team/carlos-barriga.png',
    faculty: 'Facultad de Artes',
    location: 'Sede Bogotá',
    email: 'correounal@unal.edu.co',
  },
  {
    name: 'Claudia Patricia Sierra Pardo',
    image: '/images/about-us/team/claudia-sierra.png',
    faculty: 'Facultad de Ciencias Humanas',
    location: 'Sede Bogotá',
    email: 'correounal@unal.edu.co',
  },
  {
    name: 'Fabio Rodrigo Leiva Barón',
    image: '/images/about-us/team/fabio-leiva.png',
    faculty: 'Facultad de Ciencias Agrarias',
    location: 'Sede Bogotá',
    email: 'frleivab@unal.edu.co',
  },
  // {
  //   name: 'James León Parra-Monsalve',
  //   image: '/images/about-us/team/doris-santos.jpeg',
  //   faculty: 'Dir. Académica Com. Social/Historia',
  //   location: 'Sede La Paz',
  //   email: 'jlparram@unal.edu.co',
  // },
  {
    name: 'Jovani Alberto Jiménez Builes',
    image: '/images/about-us/team/jovani-jimenez.png',
    faculty: 'Facultad de Minas',
    location: 'Sede Medellín',
    email: 'jajimen1@unal.edu.co',
  },
  {
    name: 'Jairo Humberto Lopez',
    image: '/images/about-us/team/jairo-lopez.jpg',
    faculty: 'Facultad de Ciencias',
    location: 'Sede Bogotá',
    email: 'correounal@unal.edu.co',
  },
  // {
  //   name: 'Karol Bibiana Barragán Fonseca',
  //   image: '/images/about-us/team/doris-santos.jpeg',
  //   faculty: 'Fac. de Medicina Veterinaria y Zootecnia',
  //   location: 'Sede Bogotá',
  //   email: 'kbbarraganf@unal.edu.co',
  // },
  {
    name: 'Maria Clemencia Castro Vergara',
    image: '/images/about-us/team/maria-castro.png',
    faculty: 'Facultad de Ciencias Humanas',
    location: 'Sede Bogotá',
    email: 'mccastrov@unal.edu.co',
  },
  {
    name: 'Marina Sánchez de Praguer',
    image: '/images/about-us/team/maria-sanchez.png',
    faculty: 'Facultad de Ingeniería y Administración',
    location: 'Sede Palmira',
    email: 'msanchezpr@unal.edu.co',
  },
  {
    name: 'Mario Esteban Hernández Álvarez',
    image: '/images/about-us/team/mario-hernandez.png',
    faculty: 'Facultad de Medicina',
    location: 'Sede Bogotá',
    email: 'mehernandeza@unal.edu.co',
  },
  {
    name: 'Rafael Antonio Malagón Oviedo',
    image: '/images/about-us/team/man-default.jpg',
    faculty: 'Facultad de Odontología',
    location: 'Sede Bogotá',
    email: 'ramalagono@unal.edu.co',
  },
]
.map((person, index) => ({
  ...person,
  id: index + 1 ,
  slug: person.name.split(' ').map((w) => w.toLowerCase()).join('-'),
}));

export default TEAM_MEMBERS;
