export type RedArea = 'all'
                    | 'videos'
                    | 'podcast'
                    | 'articles'
                    | 'training'
                    | 'events'
                    | 'others'
                    | 'processes'
                    | 'science'
                    | 'art'
                    | 'health'
                    | 'territory'
                    | 'victims'
                    | 'agreements'
                    | 'citizenship';
