// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutUs: typeof import('./views/about-us/AboutUs.vue')['default']
    ActivitiesRedPaz: typeof import('./views/experiences/activities/ActivitiesRedPaz.vue')['default']
    BannerItem: typeof import('./common/components/BannerItem.vue')['default']
    BaseItem: typeof import('./common/components/BaseItem.vue')['default']
    DescriptionSection: typeof import('./common/components/DescriptionSection.vue')['default']
    DescriptionVideo: typeof import('./common/components/DescriptionVideo.vue')['default']
    DiscussionActivities: typeof import('./views/experiences/activities/DiscussionActivities.vue')['default']
    ENEP: typeof import('./views/experiences/activities/ENEP.vue')['default']
    EpisodeItem: typeof import('./common/components/EpisodeItem.vue')['default']
    Experiences: typeof import('./views/experiences/Experiences.vue')['default']
    FeaturedItem: typeof import('./common/components/FeaturedItem.vue')['default']
    FooterUnal: typeof import('./common/components/FooterUnal.vue')['default']
    GridSection: typeof import('./common/components/GridSection.vue')['default']
    HeaderUnal: typeof import('./common/components/HeaderUnal.vue')['default']
    Home: typeof import('./views/Home.vue')['default']
    IMdiCalendarMonth: typeof import('~icons/mdi/calendar-month')['default']
    IMdiCheck: typeof import('~icons/mdi/check')['default']
    IMdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    IMdiMenuDown: typeof import('~icons/mdi/menu-down')['default']
    IMdiRadioTower: typeof import('~icons/mdi/radio-tower')['default']
    IMdiSpotify: typeof import('~icons/mdi/spotify')['default']
    IMdiYoutube: typeof import('~icons/mdi/youtube')['default']
    ItemWithImage: typeof import('./common/components/ItemWithImage.vue')['default']
    JobAreas: typeof import('./common/components/JobAreas.vue')['default']
    MainLayout: typeof import('./common/layouts/MainLayout.vue')['default']
    MiniserieActivity: typeof import('./views/experiences/activities/MiniserieActivity.vue')['default']
    PageHeader: typeof import('./common/components/PageHeader.vue')['default']
    PersonItem: typeof import('./common/components/PersonItem.vue')['default']
    PictureNew: typeof import('./common/components/PictureNew.vue')['default']
    PodcastActivities: typeof import('./views/experiences/activities/PodcastActivities.vue')['default']
    Profile: typeof import('./views/about-us/Profile.vue')['default']
    RedSlider: typeof import('./common/components/RedSlider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionDecoration: typeof import('./common/components/SectionDecoration.vue')['default']
    YoutubeItem: typeof import('./common/components/YoutubeItem.vue')['default']
  }
}
