// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutUs: typeof import('./views/AboutUs.vue')['default']
    BannerItem: typeof import('./common/components/BannerItem.vue')['default']
    BaseItem: typeof import('./common/components/BaseItem.vue')['default']
    DescriptionSection: typeof import('./common/components/DescriptionSection.vue')['default']
    FooterUnal: typeof import('./common/components/FooterUnal.vue')['default']
    GridColumnItems: typeof import('./common/components/GridColumnItems.vue')['default']
    GridSection: typeof import('./common/components/GridSection.vue')['default']
    HeaderUnal: typeof import('./common/components/HeaderUnal.vue')['default']
    Home: typeof import('./views/Home.vue')['default']
    IMdiChevronLeft: typeof import('~icons/mdi/chevron-left')['default']
    IMdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    IMdiEmailOutline: typeof import('~icons/mdi/email-outline')['default']
    IMdiMagnify: typeof import('~icons/mdi/magnify')['default']
    IMdiMenuDown: typeof import('~icons/mdi/menu-down')['default']
    IMdiPhoneOutline: typeof import('~icons/mdi/phone-outline')['default']
    ItemWithImage: typeof import('./common/components/ItemWithImage.vue')['default']
    PageHeader: typeof import('./common/components/PageHeader.vue')['default']
    PersonItem: typeof import('./common/components/PersonItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
