// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutUs: typeof import('./views/AboutUs.vue')['default']
    ActivitiesRedPaz: typeof import('./views/experiences/activities/ActivitiesRedPaz.vue')['default']
    BannerItem: typeof import('./common/components/BannerItem.vue')['default']
    BaseItem: typeof import('./common/components/BaseItem.vue')['default']
    DescriptionSection: typeof import('./common/components/DescriptionSection.vue')['default']
    DiscussionActivities: typeof import('./views/experiences/activities/DiscussionActivities.vue')['default']
    EpisodeItem: typeof import('./common/components/EpisodeItem.vue')['default']
    ExperiencesWrapper: typeof import('./views/experiences/ExperiencesWrapper.vue')['default']
    FooterUnal: typeof import('./common/components/FooterUnal.vue')['default']
    GridColumnItems: typeof import('./common/components/GridColumnItems.vue')['default']
    GridSection: typeof import('./common/components/GridSection.vue')['default']
    HeaderUnal: typeof import('./common/components/HeaderUnal.vue')['default']
    Home: typeof import('./views/Home.vue')['default']
    'IMdi-${key}': typeof import('~icons/mdi/${key}')['default']
    IMdiCalendarMonth: typeof import('~icons/mdi/calendar-month')['default']
    IMdiCheck: typeof import('~icons/mdi/check')['default']
    IMdiChevronLeft: typeof import('~icons/mdi/chevron-left')['default']
    IMdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    IMdiEmailOutline: typeof import('~icons/mdi/email-outline')['default']
    IMdiMagnify: typeof import('~icons/mdi/magnify')['default']
    IMdiMenuDown: typeof import('~icons/mdi/menu-down')['default']
    IMdiPhoneOutline: typeof import('~icons/mdi/phone-outline')['default']
    IMdiRadio: typeof import('~icons/mdi/radio')['default']
    IMdiRadioTower: typeof import('~icons/mdi/radio-tower')['default']
    IMdiSpotify: typeof import('~icons/mdi/spotify')['default']
    IMdiYoutube: typeof import('~icons/mdi/youtube')['default']
    ItemWithImage: typeof import('./common/components/ItemWithImage.vue')['default']
    MiniserieActivity: typeof import('./views/experiences/activities/MiniserieActivity.vue')['default']
    PageHeader: typeof import('./common/components/PageHeader.vue')['default']
    PersonItem: typeof import('./common/components/PersonItem.vue')['default']
    PodcastActivities: typeof import('./views/experiences/activities/PodcastActivities.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionDecoration: typeof import('./common/components/SectionDecoration.vue')['default']
  }
}
